//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pruebas_EMP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pruebas_EMP()
        {
            this.Pruebas_EmpleadosControlHoras = new HashSet<Pruebas_EmpleadosControlHoras>();
            this.Pruebas_SolicitarToken_CambioPassword = new HashSet<Pruebas_SolicitarToken_CambioPassword>();
        }
    
        public int Id { get; set; }
        public string NombreEmpleado { get; set; }
        public int EdadEmpleado { get; set; }
        public string SexoEmpleado { get; set; }
        public int IdPuesto { get; set; }
        public byte[] FotografiaEmpleado { get; set; }
        public string Extension { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<int> NumTelefono { get; set; }
        public Nullable<int> Intentos { get; set; }
        public string Email { get; set; }
        public byte[] Password { get; set; }
    
        public virtual Pruebas_EstadoUsuario Pruebas_EstadoUsuario { get; set; }
        public virtual Pruebas_PRS Pruebas_PRS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pruebas_EmpleadosControlHoras> Pruebas_EmpleadosControlHoras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pruebas_SolicitarToken_CambioPassword> Pruebas_SolicitarToken_CambioPassword { get; set; }
    }
}
