//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PruebasEntities : DbContext
    {
        public PruebasEntities()
            : base("name=PruebasEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pruebas_EmailsLog> Pruebas_EmailsLog { get; set; }
        public virtual DbSet<Pruebas_EmpleadosControlHoras> Pruebas_EmpleadosControlHoras { get; set; }
        public virtual DbSet<Pruebas_EstadoUsuario> Pruebas_EstadoUsuario { get; set; }
        public virtual DbSet<Pruebas_PRS> Pruebas_PRS { get; set; }
        public virtual DbSet<Pruebas_SolicitarToken_CambioPassword> Pruebas_SolicitarToken_CambioPassword { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Pruebas_EMP> Pruebas_EMP { get; set; }
    
        [DbFunction("PruebasEntities2", "Pruebas_CotrolHoras")]
        public virtual IQueryable<Pruebas_CotrolHoras_Result> Pruebas_CotrolHoras(Nullable<int> idEmpleado, Nullable<System.DateTime> desde, Nullable<System.DateTime> hasta)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            var desdeParameter = desde.HasValue ?
                new ObjectParameter("Desde", desde) :
                new ObjectParameter("Desde", typeof(System.DateTime));
    
            var hastaParameter = hasta.HasValue ?
                new ObjectParameter("Hasta", hasta) :
                new ObjectParameter("Hasta", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_CotrolHoras_Result>("[PruebasEntities2].[Pruebas_CotrolHoras](@IdEmpleado, @Desde, @Hasta)", idEmpleadoParameter, desdeParameter, hastaParameter);
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_FN_ControlHoras")]
        public virtual IQueryable<Pruebas_FN_ControlHoras_Result> Pruebas_FN_ControlHoras(Nullable<int> idEmpleado)
        {
            var idEmpleadoParameter = idEmpleado.HasValue ?
                new ObjectParameter("IdEmpleado", idEmpleado) :
                new ObjectParameter("IdEmpleado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_FN_ControlHoras_Result>("[PruebasEntities2].[Pruebas_FN_ControlHoras](@IdEmpleado)", idEmpleadoParameter);
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_FN_ImagenUnEmpleado")]
        public virtual IQueryable<Pruebas_FN_ImagenUnEmpleado_Result> Pruebas_FN_ImagenUnEmpleado(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_FN_ImagenUnEmpleado_Result>("[PruebasEntities2].[Pruebas_FN_ImagenUnEmpleado](@Id)", idParameter);
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_FN_Login_User")]
        public virtual IQueryable<Pruebas_FN_Login_User_Result> Pruebas_FN_Login_User(string email, string password)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_FN_Login_User_Result>("[PruebasEntities2].[Pruebas_FN_Login_User](@Email, @Password)", emailParameter, passwordParameter);
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_FN_TraerEstado")]
        public virtual IQueryable<Pruebas_FN_TraerEstado_Result> Pruebas_FN_TraerEstado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_FN_TraerEstado_Result>("[PruebasEntities2].[Pruebas_FN_TraerEstado]()");
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_SoloUnEmpleado")]
        public virtual IQueryable<Pruebas_SoloUnEmpleado_Result> Pruebas_SoloUnEmpleado(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_SoloUnEmpleado_Result>("[PruebasEntities2].[Pruebas_SoloUnEmpleado](@Id)", idParameter);
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_TodosEmpleados")]
        public virtual IQueryable<Pruebas_TodosEmpleados_Result> Pruebas_TodosEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_TodosEmpleados_Result>("[PruebasEntities2].[Pruebas_TodosEmpleados]()");
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_TraerPuestos")]
        public virtual IQueryable<Pruebas_TraerPuestos_Result> Pruebas_TraerPuestos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_TraerPuestos_Result>("[PruebasEntities2].[Pruebas_TraerPuestos]()");
        }
    
        public virtual int Pruebas_CrearEmpleado(string nombreEmpleado, Nullable<int> edadEmpleado, string sexoEmpleado, Nullable<int> idPuesto, byte[] fotografiaEmpleado)
        {
            var nombreEmpleadoParameter = nombreEmpleado != null ?
                new ObjectParameter("NombreEmpleado", nombreEmpleado) :
                new ObjectParameter("NombreEmpleado", typeof(string));
    
            var edadEmpleadoParameter = edadEmpleado.HasValue ?
                new ObjectParameter("EdadEmpleado", edadEmpleado) :
                new ObjectParameter("EdadEmpleado", typeof(int));
    
            var sexoEmpleadoParameter = sexoEmpleado != null ?
                new ObjectParameter("SexoEmpleado", sexoEmpleado) :
                new ObjectParameter("SexoEmpleado", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var fotografiaEmpleadoParameter = fotografiaEmpleado != null ?
                new ObjectParameter("FotografiaEmpleado", fotografiaEmpleado) :
                new ObjectParameter("FotografiaEmpleado", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_CrearEmpleado", nombreEmpleadoParameter, edadEmpleadoParameter, sexoEmpleadoParameter, idPuestoParameter, fotografiaEmpleadoParameter);
        }
    
        public virtual int Pruebas_EditarEmpleado(Nullable<int> id, string nombreEmpleado, Nullable<int> edadEmpleado, Nullable<int> numTelefono, string sexoEmpleado, string email, Nullable<int> idPuesto, Nullable<int> idEstado, byte[] fotografiaEmpleado, string extension, ObjectParameter mensaje, ObjectParameter status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreEmpleadoParameter = nombreEmpleado != null ?
                new ObjectParameter("NombreEmpleado", nombreEmpleado) :
                new ObjectParameter("NombreEmpleado", typeof(string));
    
            var edadEmpleadoParameter = edadEmpleado.HasValue ?
                new ObjectParameter("EdadEmpleado", edadEmpleado) :
                new ObjectParameter("EdadEmpleado", typeof(int));
    
            var numTelefonoParameter = numTelefono.HasValue ?
                new ObjectParameter("NumTelefono", numTelefono) :
                new ObjectParameter("NumTelefono", typeof(int));
    
            var sexoEmpleadoParameter = sexoEmpleado != null ?
                new ObjectParameter("SexoEmpleado", sexoEmpleado) :
                new ObjectParameter("SexoEmpleado", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var fotografiaEmpleadoParameter = fotografiaEmpleado != null ?
                new ObjectParameter("FotografiaEmpleado", fotografiaEmpleado) :
                new ObjectParameter("FotografiaEmpleado", typeof(byte[]));
    
            var extensionParameter = extension != null ?
                new ObjectParameter("Extension", extension) :
                new ObjectParameter("Extension", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_EditarEmpleado", idParameter, nombreEmpleadoParameter, edadEmpleadoParameter, numTelefonoParameter, sexoEmpleadoParameter, emailParameter, idPuestoParameter, idEstadoParameter, fotografiaEmpleadoParameter, extensionParameter, mensaje, status);
        }
    
        public virtual int Pruebas_EliminarEmpleado(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_EliminarEmpleado", idParameter);
        }
    
        public virtual int Pruebas_P_CrearEmpleado(string nombreEmpleado, Nullable<int> edadEmpleado, string sexoEmpleado, byte[] password, Nullable<int> numTelefono, string email, Nullable<int> idPuesto, Nullable<int> idEstado, byte[] fotografiaEmpleado, ObjectParameter mensaje, ObjectParameter status)
        {
            var nombreEmpleadoParameter = nombreEmpleado != null ?
                new ObjectParameter("NombreEmpleado", nombreEmpleado) :
                new ObjectParameter("NombreEmpleado", typeof(string));
    
            var edadEmpleadoParameter = edadEmpleado.HasValue ?
                new ObjectParameter("EdadEmpleado", edadEmpleado) :
                new ObjectParameter("EdadEmpleado", typeof(int));
    
            var sexoEmpleadoParameter = sexoEmpleado != null ?
                new ObjectParameter("SexoEmpleado", sexoEmpleado) :
                new ObjectParameter("SexoEmpleado", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            var numTelefonoParameter = numTelefono.HasValue ?
                new ObjectParameter("NumTelefono", numTelefono) :
                new ObjectParameter("NumTelefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            var idEstadoParameter = idEstado.HasValue ?
                new ObjectParameter("IdEstado", idEstado) :
                new ObjectParameter("IdEstado", typeof(int));
    
            var fotografiaEmpleadoParameter = fotografiaEmpleado != null ?
                new ObjectParameter("FotografiaEmpleado", fotografiaEmpleado) :
                new ObjectParameter("FotografiaEmpleado", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_CrearEmpleado", nombreEmpleadoParameter, edadEmpleadoParameter, sexoEmpleadoParameter, passwordParameter, numTelefonoParameter, emailParameter, idPuestoParameter, idEstadoParameter, fotografiaEmpleadoParameter, mensaje, status);
        }
    
        public virtual int Pruebas_P_Intentos_Usuario(Nullable<int> intentos, string email, Nullable<int> estado)
        {
            var intentosParameter = intentos.HasValue ?
                new ObjectParameter("Intentos", intentos) :
                new ObjectParameter("Intentos", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var estadoParameter = estado.HasValue ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_Intentos_Usuario", intentosParameter, emailParameter, estadoParameter);
        }
    
        public virtual int Pruebas_P_Recuperar_Cuenta(string email, byte[] password, Nullable<int> numTelefono, ObjectParameter mensaje, ObjectParameter status)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            var numTelefonoParameter = numTelefono.HasValue ?
                new ObjectParameter("NumTelefono", numTelefono) :
                new ObjectParameter("NumTelefono", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_Recuperar_Cuenta", emailParameter, passwordParameter, numTelefonoParameter, mensaje, status);
        }
    
        public virtual int Pruebas_P_Regristrar_Usuario_Login(string nombreEmpleado, Nullable<int> edadEmpleado, string sexoEmpleado, byte[] password, Nullable<int> numTelefono, string email, ObjectParameter mensaje, ObjectParameter status)
        {
            var nombreEmpleadoParameter = nombreEmpleado != null ?
                new ObjectParameter("NombreEmpleado", nombreEmpleado) :
                new ObjectParameter("NombreEmpleado", typeof(string));
    
            var edadEmpleadoParameter = edadEmpleado.HasValue ?
                new ObjectParameter("EdadEmpleado", edadEmpleado) :
                new ObjectParameter("EdadEmpleado", typeof(int));
    
            var sexoEmpleadoParameter = sexoEmpleado != null ?
                new ObjectParameter("SexoEmpleado", sexoEmpleado) :
                new ObjectParameter("SexoEmpleado", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(byte[]));
    
            var numTelefonoParameter = numTelefono.HasValue ?
                new ObjectParameter("NumTelefono", numTelefono) :
                new ObjectParameter("NumTelefono", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_Regristrar_Usuario_Login", nombreEmpleadoParameter, edadEmpleadoParameter, sexoEmpleadoParameter, passwordParameter, numTelefonoParameter, emailParameter, mensaje, status);
        }
    
        public virtual int Pruebas_P_Set_EmailsLog(string destinatario, string asunto, string mensaje)
        {
            var destinatarioParameter = destinatario != null ?
                new ObjectParameter("Destinatario", destinatario) :
                new ObjectParameter("Destinatario", typeof(string));
    
            var asuntoParameter = asunto != null ?
                new ObjectParameter("Asunto", asunto) :
                new ObjectParameter("Asunto", typeof(string));
    
            var mensajeParameter = mensaje != null ?
                new ObjectParameter("Mensaje", mensaje) :
                new ObjectParameter("Mensaje", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_Set_EmailsLog", destinatarioParameter, asuntoParameter, mensajeParameter);
        }
    
        public virtual int Pruebas_P_SolicitarToken_CambioPassword(string email, string dispositivo, string token, string key, Nullable<System.DateTime> fechaSolicitud, Nullable<System.DateTime> fechaExpiracion, Nullable<int> emailSend, ObjectParameter mensaje, ObjectParameter status)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var dispositivoParameter = dispositivo != null ?
                new ObjectParameter("Dispositivo", dispositivo) :
                new ObjectParameter("Dispositivo", typeof(string));
    
            var tokenParameter = token != null ?
                new ObjectParameter("Token", token) :
                new ObjectParameter("Token", typeof(string));
    
            var keyParameter = key != null ?
                new ObjectParameter("Key", key) :
                new ObjectParameter("Key", typeof(string));
    
            var fechaSolicitudParameter = fechaSolicitud.HasValue ?
                new ObjectParameter("FechaSolicitud", fechaSolicitud) :
                new ObjectParameter("FechaSolicitud", typeof(System.DateTime));
    
            var fechaExpiracionParameter = fechaExpiracion.HasValue ?
                new ObjectParameter("FechaExpiracion", fechaExpiracion) :
                new ObjectParameter("FechaExpiracion", typeof(System.DateTime));
    
            var emailSendParameter = emailSend.HasValue ?
                new ObjectParameter("EmailSend", emailSend) :
                new ObjectParameter("EmailSend", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_SolicitarToken_CambioPassword", emailParameter, dispositivoParameter, tokenParameter, keyParameter, fechaSolicitudParameter, fechaExpiracionParameter, emailSendParameter, mensaje, status);
        }
    
        public virtual int Pruebas_SP_EditarEmpleado(Nullable<int> id, string nombreEmpleado, Nullable<int> edadEmpleado, string sexoEmpleado, Nullable<int> idPuesto)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nombreEmpleadoParameter = nombreEmpleado != null ?
                new ObjectParameter("NombreEmpleado", nombreEmpleado) :
                new ObjectParameter("NombreEmpleado", typeof(string));
    
            var edadEmpleadoParameter = edadEmpleado.HasValue ?
                new ObjectParameter("EdadEmpleado", edadEmpleado) :
                new ObjectParameter("EdadEmpleado", typeof(int));
    
            var sexoEmpleadoParameter = sexoEmpleado != null ?
                new ObjectParameter("SexoEmpleado", sexoEmpleado) :
                new ObjectParameter("SexoEmpleado", typeof(string));
    
            var idPuestoParameter = idPuesto.HasValue ?
                new ObjectParameter("IdPuesto", idPuesto) :
                new ObjectParameter("IdPuesto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_SP_EditarEmpleado", idParameter, nombreEmpleadoParameter, edadEmpleadoParameter, sexoEmpleadoParameter, idPuestoParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        [DbFunction("PruebasEntities2", "Pruebas_FN_TodosEmpleados")]
        public virtual IQueryable<Pruebas_FN_TodosEmpleados_Result> Pruebas_FN_TodosEmpleados()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Pruebas_FN_TodosEmpleados_Result>("[PruebasEntities2].[Pruebas_FN_TodosEmpleados]()");
        }
    
        public virtual int Pruebas_P_Actualizar_Estado_Token(string email)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Pruebas_P_Actualizar_Estado_Token", emailParameter);
        }
    }
}
